### ISSUE TITLE
TypeError: unexpected keyword argument 'metadata_transformer'

### ISSUE THREAD

**Issue by sansan88** [fableh/sap_cp_leonardo_ml_fnd_byom#1]
I got the following error:
TypeError: beta_create_PredictionService_stub() got an unexpected keyword argument 'metadata_transformer'

Dump:
[2018-08-17 18:28:12,070] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/mnt/c/Users/John/Desktop/TensorFlow/byom/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/John/Desktop/TensorFlow/byom/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/John/Desktop/TensorFlow/byom/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/John/Desktop/TensorFlow/byom/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/John/Desktop/TensorFlow/byom/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 41, in main
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel, metadata_transformer=metadata_transformer)
TypeError: beta_create_PredictionService_stub() got an unexpected keyword argument 'metadata_transformer'
127.0.0.1 - - [17/Aug/2018 18:28:12] "POST / HTTP/1.1" 500 -

has there something changed?

**Comment by rafiqhasan** [comment]
same here !..

Tensorflow's library has changed so this parameter is no more available. You can comment it out.

`stub = prediction_service_pb2.beta_create_PredictionService_stub(channel, metadata_transformer=metadata_transformer`
